In [1]:
import numpy as np

# Arange
Es similar al metodo range, tiene como finalidad generar arrays

In [4]:
array=np.arange(5)
array #Genera una secuencia de elementos de 0 a valor insertado menos uno

array([0, 1, 2, 3, 4])

In [7]:
array=np.arange(2,15)
array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
array=np.arange(2,40,2)
array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [16]:
array=np.zeros((3,1))#Filas,Columnas
array

array([[0.],
       [0.],
       [0.]])

In [18]:
array=np.ones(2)
array

array([1., 1.])

# Linespase
Genera una matriz con valores entre los intervalos (Los dos primeros parametros)
El ultimo parametro es el numero de elementos que se van  generar

In [20]:
array=np.linspace(9,3,50)
array

array([9.        , 8.87755102, 8.75510204, 8.63265306, 8.51020408,
       8.3877551 , 8.26530612, 8.14285714, 8.02040816, 7.89795918,
       7.7755102 , 7.65306122, 7.53061224, 7.40816327, 7.28571429,
       7.16326531, 7.04081633, 6.91836735, 6.79591837, 6.67346939,
       6.55102041, 6.42857143, 6.30612245, 6.18367347, 6.06122449,
       5.93877551, 5.81632653, 5.69387755, 5.57142857, 5.44897959,
       5.32653061, 5.20408163, 5.08163265, 4.95918367, 4.83673469,
       4.71428571, 4.59183673, 4.46938776, 4.34693878, 4.2244898 ,
       4.10204082, 3.97959184, 3.85714286, 3.73469388, 3.6122449 ,
       3.48979592, 3.36734694, 3.24489796, 3.12244898, 3.        ])

# Eye 
Genera una matriz de dos dimensiones 

In [25]:
array=np.eye(6)
array

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])