In [1]:
import numpy as np

In [2]:
np.random.rand(5)

array([0.77163185, 0.07674659, 0.5254232 , 0.01772149, 0.58837433])

In [4]:
np.random.rand(3,5)#Tres filas y cinco columnas

array([[0.44623173, 0.4533934 , 0.08053392, 0.49329359, 0.55443769],
       [0.66859865, 0.75844959, 0.72866691, 0.25706421, 0.74187275],
       [0.82246407, 0.44746676, 0.08962219, 0.71437949, 0.99028951]])

Se utiliza el metodo randn para arrojar una matriz con una distrubucion normal

In [13]:
edades=12+5*np.random.randn(3,7)

In [14]:
edades

array([[11.73624646, 12.60308778, 14.69729522, 16.52180508,  6.96356221,
        17.80217104, 15.6908014 ],
       [ 9.15233659, 18.01332642, 17.16478739, 21.23917778, 13.85015701,
        16.59989664,  6.21634081],
       [13.97179121, 11.06831368, 18.84894688, 18.50670039,  7.66200548,
        12.38865731, 15.93435734]])